### ISSUE TITLE
関西CoderDojoカレンダーの挿入

### ISSUE THREAD

**Issue by KazukiHigashi** [coderdojo-akashi/coderdojo-akashi.github.io#25]
こり。
https://calendar.google.com/calendar/embed?src=0ap865g5sqqktm38hjci4g8d44%40group.calendar.google.com&ctz=Asia%2FTokyo

**Comment by tatsukawa** [comment]
おっと見てなかった．やります

**Comment by tatsukawa** [comment]
5c38e2158961f24f3a290ca042d848329e354c4c
